name: Create release assets

on:
  release:
    types:
      - published

jobs:
  build:
    name: Create release assets
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Check out the source repository
        uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Install dependencies
        run: >
          sudo apt-get install -y
          libboost-dev
          libboost-json-dev
          libc-ares-dev
          libcap-dev
          libgrpc++-dev
          libmnl-dev
          libncurses-dev
          libprotobuf-dev
          libre2-dev
          libtomlplusplus-dev
          pandoc
          protobuf-compiler
          protobuf-compiler-grpc
      - name: Configure
        run: |
          mkdir build
          cmake -G 'Ninja Multi-Config' -B build -DCPACK_SET_DESTDIR=ON -DCMAKE_INSTALL_PREFIX=/ -DRELEASE=YES
      - name: Build deb packages
        run: make deb
      - name: Combine checksum files
        run: cat out/*.sha256 > out/checksums.sha256
      - name: Upload release assets
        uses: softprops/action-gh-release@v2.5.0
        with:
          overwrite_files: false
          preserve_order: true
          generate_release_notes: false
          files: |
            out/*.deb
            out/checksum.sha256
