name: Run tests

on:
  push:
    branch: main
  pull_request:

jobs:
  tests-linux:
    name: Run tests (Linux)
    runs-on: ubuntu-24.04
    steps:
      - name: Check out the source repository
        uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Install dependencies
        run: >
          sudo apt-get install -y
          libboost-dev
          libboost-json-dev
          libc-ares-dev
          libcap-dev
          libgrpc++-dev
          libmnl-dev
          libncurses-dev
          libprotobuf-dev
          libre2-dev
          libtomlplusplus-dev
          pandoc
          protobuf-compiler
          protobuf-compiler-grpc
      - name: Configure
        run: |
          mkdir build
          cmake -G 'Ninja Multi-Config' -B build
      - name: Build
        id: build
        run: cmake --build build --config Debug
      - name: SCION++ tests
        if: steps.build.conclusion == 'success'
        run: make test
      - name: Scitra tests
        if: steps.build.conclusion == 'success'
        run: make test-scitra
      - name: Interposer tests
        if: steps.build.conclusion == 'success'
        run: make test-interposer
      - name: Checkout SCION
        uses: actions/checkout@v6
        with:
          repository: 'scionproto/scion'
          path: 'scion'
          ref: v0.14.0
      - name: Build SCION
        working-directory: '${{ github.workspace }}/scion'
        run: >
          CGO_ENABLED=0 go build -o bin ./router/... ./control/... ./dispatcher/... ./daemon/...
          ./scion/... ./scion-pki/...
      - name: Run integration tests
        run: make SCION_ROOT=${{ github.workspace }}/scion test-integration

  unit-tests-windows:
    name: Run unit tests (Windows)
    runs-on: windows-latest
    # Disabled because building gRPC with vcpkg consumes too many resources
    # See: https://github.com/microsoft/vcpkg/issues/43603
    # if: false
    steps:
      - name: Check out the source repository
        uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Get CMake and Ninja
        uses: lukka/get-cmake@latest
      - name: Install dependencies with vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: a20d95d3c76906363896754eb1cc93db2a694f16
      - name: Configure
        uses: lukka/run-cmake@v10
        with:
          configurePreset: vcpkg-vs
      - name: Build
        id: build
        run: cmake --build build --config Debug
      - name: SCION++ tests
        if: steps.build.conclusion == 'success'
        run: .\build\Debug\unit-tests.exe .\tests
      - name: Scitra tests
        if: steps.build.conclusion == 'success'
        run: .\build\scitra\Debug\scitra-tests.exe .\scitra\tests
